map_height: 9
map_width: 9
n_actions: 8
reward_states: [[8, 8]]
terminal_states: [[8, 8]]
unsafe_states: [[2,0], [2,1], [2,2], [2,3], [2,4], [2,5], [2,6],
                [6,2], [6,3], [6,4], [6,5], [6,6], [6,7], [6,8],]
start_states: [[0,0]]
wind_direction: 'u'
wind_strength: 0.1